### ISSUE TITLE
When using the security plugin and goakit plugin the generated SecureDecodeFooBarRequest is not compatible with go-kit's DecodeRequestFunc type

### ISSUE THREAD

**Issue by nicholaslam** [goadesign/plugins#36]
When using the security plugin there are generated secure request decoders e.g. `SecureDecodeFooBarRequest`. However, they don’t work with go-kit endpoints because the return value is `func(*http.Request) (interface{}, error)` and not go-kit’s `DecodeRequestFunc` which is `func(context.Context, *http.Request) (request interface{}, err error)`.

My current workaround is to wrap the secure request decoders:
```go
var dec = goahttp.RequestDecoder

func genericDecodeRequestFunc(muxRouter goahttp.Muxer, secureDecodeRequestFunc func(goahttp.Muxer, func(*http.Request) goahttp.Decoder) func(*http.Request) (interface{}, error)) kithttp.DecodeRequestFunc {
	return func(ctx context.Context, r *http.Request) (interface{}, error) {
		return secureDecodeRequestFunc(muxRouter, dec)(r)
	}
}
```

**Comment by nitinmohan87** [comment]
Thanks @nicholaslam for reporting the issue. Not sure I understand correctly. When I use both goakit and security plugins in my design I see this method in `gen/http/dummy/kitserver/encode_decode.go`
```
func DecodeIndexRequest(mux goahttp.Muxer, decoder func(*http.Request) goahttp.Decoder) kithttp.DecodeRequestFunc {
  dec := server.DecodeIndexRequest(mux, decoder)
  return func(ctx context.Context, r *http.Request) (interface{}, error) {
    r = r.WithContext(ctx)
    return dec(r)
  }
}
```
which is then called in service main.go
```
dummyIndexHandler = kithttp.NewServer(
      endpoint.Endpoint(dummyEndpoints.Index),
      dummysvckitsvr.DecodeIndexRequest(mux, dec),
      dummysvckitsvr.EncodeIndexResponse(enc),
    )
```
Although there seems to be a bug in the goakit plugin which uses the unsecure decoder in the kitserver/encode_decode.go instead of the secure decoder. But I am not seeing the issue you mention. I am also able to compile and run my service without any issues. Would it be possible for you to post your design here so that I can try to reproduce? Thanks.

**Comment by nitinmohan87** [comment]
Just a random guess. Did you run `goa example` after importing the goakit plugin? I am wondering if encoders and decoders in service main.go is not correctly set up in your app.

**Comment by nicholaslam** [comment]
@nitinmohan87 Thank you for your prompt response.

>Although there seems to be a bug in the goakit plugin which uses the unsecure decoder in the kitserver/encode_decode.go instead of the secure decoder

Sorry, I was not clear in my issue. That is the issue I was trying to raise. It would be nice if `gen/http/dummy/kitserver/encode_decode.go` had secure decoders.

**Comment by raphael** [comment]
Thanks for the fix @nitinmohan87! - @nicholaslam can you confirm the latest plugins behave like you would expect? If not please re-open the issue. Thank you!
